name: Publish docs to Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  run:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:  
      # - name: Checkout repository
      #   uses: actions/checkout@v3


      - name: Clone Repo
        run: |
          git clone https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/nanos/FediFetcher-docs.git
          cd FediFetcher-docs
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Add Wiki Remote
        run: git remote add origin https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/nanos/FediFetcher.wiki.git
      - name: Sync content
        run: |
          git config user.name wiki-bot
          git config user.email bot@thms.uk
          git fetch origin
          git fetch upstream
          git switch master
          git merge upstream/master --no-edit
      - name: Push content
        run: |
          git push origin HEAD:master > /dev/null 2>&1
          git push upstream HEAD:master > /dev/null 2>&1