name: Publish docs to Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Pull content from wiki
        run: |
          git config user.name wiki-bot
          git config user.email bot@thms.uk
          remote remove origin
          remote add origin https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/nanos/FediFetcher-docs.git > /dev/null 2>&1
          remote add upstream https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/nanos/FediFetcher.wiki.git > /dev/null 2>&1
          git fetch origin
          git fetch upstream
          git merge upstream/master --no-edit
          git push origin HEAD:master > /dev/null 2>&1
          git push upstream HEAD:master > /dev/null 2>&1