name: Publish docs to Wiki

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:  
      - name: Clone Repo
        run: |
          git clone https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/nanos/FediFetcher-docs.git
          cd FediFetcher-docs
          git remote add upstream https://${{ secrets.WIKI_ACTION_TOKEN }}@github.com/nanos/FediFetcher.wiki.git
          git fetch origin
          git fetch upstream
          git switch master
          git merge upstream/master --no-edit
          git push origin HEAD:master > /dev/null 2>&1
          git push upstream HEAD:master > /dev/null 2>&1